{{- define "default-template.configmap.tpl" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-configmap"
data: {}
{{- end -}}
{{- define "default-template.configmap" -}}
{{- include "default-template.util.merge" (append . "default-template.configmap.tpl") -}}
{{- end -}}