{{- define "default-template.deployment.tpl" -}}
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}
{{- end -}}
{{- define "default-template.deployment" -}}
{{- include "default-template.util.merge" (append . "default-template.deployment.tpl") -}}
{{- end -}}